### ISSUE TITLE
At-rules within a nested block

### ISSUE THREAD

**Issue by aaronbushnell** [davidtheclark/stylelint-statement-max-nesting-depth#4]
We use the BEM naming scheme when creating modules so it's pretty common to see something like this

``` scss
.module {
    padding: 1rem;

    @media (min-width: 50em) {
        padding: 2rem;
    }

    &__element {
        font-size: 1.25rem;

        @media (min-width: 50em) {
            font-size: 2rem;
        }
    }
}
```

Is there a way to allow at-rules within a nested block, but not _another_ element?

``` scss
.module {
    &__element {
        font-size: 1.25rem;

        // Allow this
        @media (min-width: 50em) {
            font-size: 2rem;
        }

        // Disallow this
        &__another-element {
            color: green;
        }
    }
}
```

**Update**: Here's my current .stylelintrc (adjusted for only the relevant rule)

``` json
{
  "plugins": {
    "statement-max-nesting-depth": "stylelint-statement-max-nesting-depth"
  },
  "rules": {
    "statement-max-nesting-depth": [2, 1, { "atRulesDontCount": true }]
  }
}
```
